# The parameters "input", "output", "reference" and "primer" are the absolute paths. Do not include the "/" at the end of the paths.
input          : "/blue/bphl-florida/dongyibo/Dev_mycoplasma/git2/fastqs"
output    : "/blue/bphl-florida/dongyibo/Dev_mycoplasma/git2/output"
reference      : "/blue/bphl-florida/dongyibo/Dev_mycoplasma/git2/reference"
primer    : "/blue/bphl-florida/dongyibo/Dev_mycoplasma/git2/primers"


